### ISSUE TITLE
protocol version

### ISSUE THREAD

**Issue by Teszko** [tzano/pyosio#2]
hello,
API v1 and API v2 have different feature sets, but after initializing an OpenSensorsAPI object, there is no way to switch API versions. 
So when initialized as v2,  the "get_pub_org_meta()" function for example only returns 404. 
There should be a way to use both API versions as needed. 
My recommendation would be to give each funtion a default API version.
`
def get_pub_org_meta(self, org_id, version='v1'):
` 
I could quickly implement this, if you agree.

**Comment by tzano** [comment]
Thanks @Teszko. You are right, there are two versions of the API. I missed to mention that in the documentation. However, I have already implemented the method to switch between versions using `api_client._set_version(version)`. You can find the implementation of the method [here](https://github.com/tzano/pyosio/blob/master/pyosio/osio.py#L71-L82). 

Feel free to add an example or an explanation on this part in the documentation. 

Thanks again for your time.

**Comment by Teszko** [comment]
Alright, I can live with that. Thank you for the reply.
