### ISSUE TITLE
License File

### ISSUE THREAD

**Issue by Teszko** [tzano/pyosio#4]
While the project already contains a license notice in README.md and that's perfectly acceptable, it's beneficial to add a LICENSE file. 
GitHub actively checks projects for the existence of a license file. The project then becomes available
for code searches by license type and the license becomes visible in a prominent place in the summary bar. 
![license_bar](https://help.github.com/assets/images/help/repository/repo-license-indicator.png)
You can simply create a new file in the web interface, call it LICENSE and select the MIT template in the dropdown menu which then appears. 
https://help.github.com/articles/licensing-a-repository/#detecting-a-license

**Comment by tzano** [comment]
Thanks for the tip @Teszko. I have created the files and [submitted changes](https://github.com/tzano/pyosio/commit/98608b6b6f8e72dc7cf20700dd724117c1bce3b4).

**Comment by Teszko** [comment]
Excellent. 
And thank you for the great work on this project!
